export const data_ui_json= [
    {
        name:"intro",
        title:"intro",
        rout:"/ui/intro",
        haschild:false,
    },
    {
        name:"use",
        title:"use",
        rout:"/ui/use",
        haschild:false,
    },
    {
        name:"Base",
        haschild:true,
        item:[
            {
                rout:"/ui/color",
                title:"color"
            },
            {
                rout:"/ui/grid",
                title:"grid"
            },
            {
                rout:"/ui/shadow",
                title:"Shadow"
            },
            {
                rout:"/ui/transitions",
                title:"Transitions"
            },
            {
                rout:"/ui/typography",
                title:"Typography"
            },
            {
                rout:"/ui/adaptation",
                title:"Adaptation"
            }
        ]
    },
    {
        name:"Components",
        haschild:true,
        item:[
            {
                rout:"/ui/badges",
                title:"badges"
            },
            {
                rout:"/ui/buttons",
                title:"buttons"
            },
            {
                rout:"/ui/breadcrumbs",
                title:"breadcrumbs"
            },
            {
                rout:"/ui/cards",
                title:"cards"
            }
        ]
    },
    {
        name:"Form",
        haschild:true,
        item:[
            {
                rout:"/ui/autocomplete",
                title:"autocomplete"
            },
            {
                rout:"/ui/checkboxes",
                title:"Checkboxes"
            },
            {
                rout:"/ui/chips",
                title:"chips"
            },
            {
                rout:"/ui/pickers",
                title:"Pickers"
            },
            {
                rout:"/ui/range",
                title:"range"
            },
            {
                rout:"/ui/select",
                title:"select"
            },
            {
                rout:"/ui/switch",
                title:"switch"
            },
            {
                rout:"/ui/text",
                title:"text"
            }
        ]
    }
]