name: update contributors

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: all-contributors/all-contributors-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          skip-check: true
