name: stylesheetxrelease

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v3

      # 5
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
            deno-version: v2.x
      
      # 6
      - name: deno pack
        run: deno task pack ./styles/style.css

      # 7
      - name: Upload files to Upyun
        env:
          AccessKey: ${{ secrets.AccessKey }}
          SecretAccessKey: ${{ secrets.SecretAccessKey }}
          UPX_SERVICENAME: ${{ secrets.UPX_SERVICENAME }}
        run: deno run --allow-net --allow-read  --allow-run --allow-ffi --allow-env --allow-sys ./script/public.ts
