name: stylesheetxrelease

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Deno
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x


      # 3. Install Tailwind Oxide npm package
      - name: Install Tailwind Oxide
        run: deno install -Af --name tailwind_oxide npm:@tailwindcss/oxide@4.1.13

      # 4. Pre-cache Deno dependencies (jsr:@funxdata/toolkit etc.)
      - name: Pre-cache Deno deps
        run: deno cache ./script/public.ts

      # 5. Run deno pack task (handles TS/JS & CSS via pack_tailwindcss)
      - name: deno pack
        run: deno task pack ./styles/style.css

      # 6. Upload files to Upyun
      - name: Upload files to Upyun
        env:
          AccessKey: ${{ secrets.AccessKey }}
          SecretAccessKey: ${{ secrets.SecretAccessKey }}
          UPX_SERVICENAME: ${{ secrets.UPX_SERVICENAME }}
        run: deno run --allow-net --allow-read --allow-run --allow-ffi --allow-env --allow-sys ./script/public.ts
