name: stylesheetxrelease

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Deno
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      # 3. Install Tailwind Oxide npm package
      - name: Install Tailwind Oxide
        run: deno install -Af --global --name tailwind_oxide npm:@tailwindcss/oxide@4.1.13

      # 5. Install Tailwind Oxide npm package
      - name: install tailwindcss 
        run: deno install npm:tailwindcss
      
      # 6. Run deno pack task (handles TS/JS & CSS via pack_tailwindcss)
      - name: pack theme css
        run: deno task pack ./styles/style.css

      # 7. Run deno pack task (handles TS/JS & CSS via pack_tailwindcss)
      - name: pack release css
        run: deno task pack ./styles/styles.css
      
      # 8. 同步样式
      - name: release assets
        env:
          AccessKey: ${{ secrets.AccessKey }}
          SecretAccessKey: ${{ secrets.SecretAccessKey }}
          UPX_SERVICENAME: ${{ secrets.UPX_SERVICENAME }}
        run: deno task release ./assets ui/assets
      
      # 9. 同步文档
      - name: release doccs
        env:
          AccessKey: ${{ secrets.AccessKey }}
          SecretAccessKey: ${{ secrets.SecretAccessKey }}
          UPX_SERVICENAME: ${{ secrets.UPX_SERVICENAME }}
        run: deno task release ./docs ui/docs
