name: stylesheetxrelease

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 第一步：Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 第二步：安装 Node.js 和依赖
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
            deno-version: v2.x
      
      # 第三步: 编译打包
      - name: deno pack
        run: deno task pack ./src/app.ts

      # 第四步：上传文件到 Upyun
      - name: Upload files to Upyun
        env:
          AccessKey: ${{ secrets.AccessKey }}
          SecretAccessKey: ${{ secrets.SecretAccessKey }}
          UPX_SERVICENAME: ${{ secrets.UPX_SERVICENAME }}
        run: deno run --allow-net --allow-read  --allow-run --allow-ffi --allow-env --allow-sys ./script/public.ts
